blank_issues_enabled: false
contact_links:
  - name: Feedback on other questions
    url: https://support.qq.com/products/321980
    about: Please post any other questions here
  - name: Discussion
    url: https://github.com/kongying-tavern/yuan-shen-map/discussions
    about: Please ask and answer questions here.
  - name: Support Us
    url: https://yuanshen.site/docs/support-us.html
    about: Love Genshin Impact Map? Consider supporting us.
  - name: Open Collective
    url: https://opencollective.com/genshinmap
    about: Love Genshin Impact Map? Please consider supporting us via Open Collective.
