# @See https://pages.github.com/
name: pages

on:
  # trigger deployment on every push to main branch
  push:
    branches:
      - dev
    # @See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
    paths-ignore:
      - '**/__tests__/**'
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          # choose node.js version to use
          node-version: '14'

      # @Tip: If you use yarn, please open it and delete 64-52 lines
      #
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - name: Handle yarn cache
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-${{ matrix.node }}-yarn-
      #       ${{ runner.os }}-node-
      # # install dependencies if the cache did not hit
      # - name: Install dependencies
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn --frozen-lockfile

      # cache node_modules
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      # please check out the docs of the workflow for more details
      # @See https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir
          build_dir: ./Yuanshenditu
        env:
          # @See https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
